<?php
/** @var \Mageplaza\GiftCard\Block\GiftCard\History $block */
?>
<?php
 $data = $block->getModels();
 var_dump($block->getModels());
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('History')) ?></strong></div>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <thead>
                <tr>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('code')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Amount')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
            <?php
                foreach ($data as $item){
            ?>
                <tr>
                    <td class="col id"><?= date_format(new DateTime($item['action_time']), "Y/m/d") ?></td>
                    <td class="col id"><?= $item['code'] ?></td>
                    <td class="col id"><?= '$'.$item['amount'] ?></td>
                    <td class="col id"><?= $item['action'] ?></td>
                </tr>
            <?php
                }
            ?>
            </tbody>
        </table>
    </div>
</div>
